import type { DocumentTemplateSchema } from './templateTypes';

export const NMCK_TEMPLATE = {
  kind: 'nmck',
  title: 'Обоснование НМЦК',
  fields: [
    {
      documentKind: 'nmck',
      fieldKey: 'customer',
      label: 'Заказчик',
      statePath: 'requisites.customer',
      valueType: 'text',
      required: true,
      sources: [
        { kind: 'userSettings', label: 'Профиль пользователя', path: 'customer', transforms: ['trim'] },
      ],
    },
    {
      documentKind: 'nmck',
      fieldKey: 'subject',
      label: 'Объект закупки',
      statePath: 'requisites.subject',
      valueType: 'text',
      required: true,
      sources: [
        { kind: 'currentPurchase', label: 'Текущая закупка', path: 'subject', transforms: ['trim'] },
        { kind: 'documentState', label: 'Поле документа', path: 'requisites.subject', transforms: ['trim'] },
      ],
    },
    {
      documentKind: 'nmck',
      fieldKey: 'date',
      label: 'Дата составления',
      statePath: 'requisites.date',
      valueType: 'date',
      required: true,
      sources: [
        { kind: 'currentDate', label: 'Текущая дата', transforms: ['formatDateRu'] },
        { kind: 'documentState', label: 'Поле документа', path: 'requisites.date' },
      ],
      transforms: ['formatDateRu'],
    },
    {
      documentKind: 'nmck',
      fieldKey: 'executorPosition',
      label: 'Должность подписанта',
      statePath: 'requisites.executorPosition',
      valueType: 'text',
      required: true,
      sources: [
        { kind: 'userSettings', label: 'Профиль пользователя', path: 'executorPosition', transforms: ['trim'] },
      ],
    },
    {
      documentKind: 'nmck',
      fieldKey: 'executorName',
      label: 'ФИО подписанта',
      statePath: 'requisites.executorName',
      valueType: 'text',
      required: true,
      sources: [
        { kind: 'userSettings', label: 'Профиль пользователя', path: 'executorName', transforms: ['trim'] },
      ],
      transforms: ['formatSignatureName'],
    },
    {
      documentKind: 'nmck',
      fieldKey: 'suppliers',
      label: 'Источники ценовой информации',
      statePath: 'suppliers',
      valueType: 'list',
      required: true,
      sources: [
        {
          kind: 'counterparty',
          label: 'Справочник контрагентов',
          path: 'counterparties',
          description: 'Наименование контрагента можно использовать как поставщика, реквизиты КП вводятся отдельно.',
        },
        { kind: 'documentState', label: 'Строки документа', path: 'suppliers' },
      ],
      repeatable: { statePath: 'suppliers', itemLabel: 'Поставщик', minItems: 1 },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'supplierName',
      label: 'Наименование поставщика',
      statePath: 'suppliers[].name',
      valueType: 'text',
      required: true,
      sources: [
        { kind: 'counterparty', label: 'Контрагент', path: 'companyName', transforms: ['trim'] },
        { kind: 'documentState', label: 'Поле поставщика', path: 'suppliers[].name', transforms: ['trim'] },
      ],
      repeatable: { statePath: 'suppliers', itemLabel: 'Поставщик', minItems: 1 },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'supplierKpDetails',
      label: 'Входящий номер и дата КП',
      statePath: 'suppliers[].kpDetails',
      valueType: 'text',
      required: true,
      sources: [
        { kind: 'documentState', label: 'Поле поставщика', path: 'suppliers[].kpDetails', transforms: ['trim'] },
      ],
      repeatable: { statePath: 'suppliers', itemLabel: 'Поставщик', minItems: 1 },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'positions',
      label: 'Позиции закупки',
      statePath: 'positions',
      valueType: 'table',
      required: true,
      sources: [
        { kind: 'currentPurchase', label: 'Позиции текущей закупки', path: 'positions' },
        { kind: 'documentState', label: 'Строки документа', path: 'positions' },
      ],
      repeatable: { statePath: 'positions', itemLabel: 'Позиция', minItems: 1 },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'positionName',
      label: 'Наименование позиции',
      statePath: 'positions[].name',
      valueType: 'multilineText',
      required: true,
      sources: [
        { kind: 'currentPurchase', label: 'Позиция закупки', path: 'positions[].name', transforms: ['trim'] },
        { kind: 'documentState', label: 'Поле позиции', path: 'positions[].name', transforms: ['trim'] },
      ],
      repeatable: { statePath: 'positions', itemLabel: 'Позиция', minItems: 1 },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'positionUnit',
      label: 'Единица измерения',
      statePath: 'positions[].unit',
      valueType: 'text',
      required: true,
      sources: [
        { kind: 'currentPurchase', label: 'Позиция закупки', path: 'positions[].unit', transforms: ['trim'] },
        { kind: 'fixedText', label: 'Значение по умолчанию', description: 'штука' },
      ],
      repeatable: { statePath: 'positions', itemLabel: 'Позиция', minItems: 1 },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'positionQuantity',
      label: 'Количество',
      statePath: 'positions[].quantity',
      valueType: 'number',
      required: true,
      sources: [
        { kind: 'currentPurchase', label: 'Позиция закупки', path: 'positions[].quantity' },
        { kind: 'documentState', label: 'Поле позиции', path: 'positions[].quantity' },
      ],
      repeatable: { statePath: 'positions', itemLabel: 'Позиция', minItems: 1 },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'priceMatrix',
      label: 'Цены поставщиков',
      statePath: 'prices',
      valueType: 'table',
      required: true,
      sources: [
        { kind: 'documentState', label: 'Матрица цен', path: 'prices' },
      ],
      repeatable: { statePath: 'prices', itemLabel: 'Цена позиции поставщика' },
    },
    {
      documentKind: 'nmck',
      fieldKey: 'calculationSummary',
      label: 'Расчетные показатели НМЦК',
      statePath: 'calculation',
      valueType: 'calculated',
      required: true,
      sources: [
        {
          kind: 'calculated',
          label: 'Формулы НМЦК',
          description: 'Средняя цена, СКО, коэффициент вариации, итог по средним и минимальная сумма поставщика.',
          transforms: ['formatMoney', 'formatAmountInWords'],
        },
      ],
    },
  ],
} satisfies DocumentTemplateSchema<'nmck'>;
